version: '3.2'

services:
  rust:
    build: ./.docker
    container_name: 'rust_100'
    volumes:
      - type: bind
        source: .
        target: /var/www
    environment:
      - CARGO_BUILD_TARGET_DIR=/tmp/target
    tty: true